// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ExampleRepository is an autogenerated mock type for the ExampleRepository type
type ExampleRepository struct {
	mock.Mock
}

// GetExampleName provides a mock function with given fields:
func (_m *ExampleRepository) GetExampleName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewExampleRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewExampleRepository creates a new instance of ExampleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewExampleRepository(t mockConstructorTestingTNewExampleRepository) *ExampleRepository {
	mock := &ExampleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
